//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace NightVision.Testing {
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType =true, Namespace                                 ="http://tempuri.org/XMLSchema1.xsd")]
    [XmlRoot(Namespace     ="http://tempuri.org/XMLSchema1.xsd", IsNullable =false)]
    public partial class pawnGenTrial {
    
        private int pointMultiplierField;
    
        private int maxPawnCostMultiplierField;
    
        private pawnGenTrialTrial[] trialField;
    
        private string trialIDField;
    
        /// <remarks/>
        public int pointMultiplier {
            get {
                return this.pointMultiplierField;
            }
            set {
                this.pointMultiplierField = value;
            }
        }
    
        /// <remarks/>
        public int maxPawnCostMultiplier {
            get {
                return this.maxPawnCostMultiplierField;
            }
            set {
                this.maxPawnCostMultiplierField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("trial")]
        public pawnGenTrialTrial[] trial {
            get {
                return this.trialField;
            }
            set {
                this.trialField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string trialID {
            get {
                return this.trialIDField;
            }
            set {
                this.trialIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType =true, Namespace ="http://tempuri.org/XMLSchema1.xsd")]
    public partial class pawnGenTrialTrial {
    
        private string factionNameField;
    
        private float minPointsToGenCombatGroupField;
    
        private pawnGenTrialTrialGroupGenerated[] groupGeneratedField;
    
        /// <remarks/>
        public string factionName {
            get {
                return this.factionNameField;
            }
            set {
                this.factionNameField = value;
            }
        }
    
        /// <remarks/>
        public float minPointsToGenCombatGroup {
            get {
                return this.minPointsToGenCombatGroupField;
            }
            set {
                this.minPointsToGenCombatGroupField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("groupGenerated")]
        public pawnGenTrialTrialGroupGenerated[] groupGenerated {
            get {
                return this.groupGeneratedField;
            }
            set {
                this.groupGeneratedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType =true, Namespace ="http://tempuri.org/XMLSchema1.xsd")]
    public partial class pawnGenTrialTrialGroupGenerated {
    
        private float originalPointsField;
    
        private float modifiedPointsField;
    
        private float maxPawnCostField;
    
        private pawnGenTrialTrialGroupGeneratedPawn[] pawnField;
    
        private float pointsSpentField;
    
        /// <remarks/>
        public float originalPoints {
            get {
                return this.originalPointsField;
            }
            set {
                this.originalPointsField = value;
            }
        }
    
        /// <remarks/>
        public float modifiedPoints {
            get {
                return this.modifiedPointsField;
            }
            set {
                this.modifiedPointsField = value;
            }
        }
    
        /// <remarks/>
        public float maxPawnCost {
            get {
                return this.maxPawnCostField;
            }
            set {
                this.maxPawnCostField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("pawn")]
        public pawnGenTrialTrialGroupGeneratedPawn[] pawn {
            get {
                return this.pawnField;
            }
            set {
                this.pawnField = value;
            }
        }
    
        /// <remarks/>
        public float pointsSpent {
            get {
                return this.pointsSpentField;
            }
            set {
                this.pointsSpentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType =true, Namespace ="http://tempuri.org/XMLSchema1.xsd")]
    public partial class pawnGenTrialTrialGroupGeneratedPawn {
    
        private int combatPowerField;
    
        private string labelField;
    
        private string primaryEqField;
    
        private bool hasShieldField;
    
        private string apparelChestField;
    
        private string apparelHeadField;
    
        private string hediffsField;
    
        /// <remarks/>
        public int combatPower {
            get {
                return this.combatPowerField;
            }
            set {
                this.combatPowerField = value;
            }
        }
    
        /// <remarks/>
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    
        /// <remarks/>
        public string primaryEq {
            get {
                return this.primaryEqField;
            }
            set {
                this.primaryEqField = value;
            }
        }
    
        /// <remarks/>
        public bool hasShield {
            get {
                return this.hasShieldField;
            }
            set {
                this.hasShieldField = value;
            }
        }
    
        /// <remarks/>
        public string apparelChest {
            get {
                return this.apparelChestField;
            }
            set {
                this.apparelChestField = value;
            }
        }
    
        /// <remarks/>
        public string apparelHead {
            get {
                return this.apparelHeadField;
            }
            set {
                this.apparelHeadField = value;
            }
        }
    
        /// <remarks/>
        public string hediffs {
            get {
                return this.hediffsField;
            }
            set {
                this.hediffsField = value;
            }
        }
    }
}