<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net480</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>

		<!-- Modify [RootNamespace], [AssemblyName], [OutputPath], [VersionPrefix] -->
		<RootNamespace>VengefulRage</RootNamespace>
		<AssemblyName>VengefulRage</AssemblyName>
		<OutputPath>../1.5/Assemblies</OutputPath>
		<VersionPrefix>4.0.33</VersionPrefix>
		<DebugSymbols>false</DebugSymbols>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<!-- Mod -->
		<Compile Include="../Source/*" />
		<!-- Rimworld -->
		<Reference Include="../../../RimWorldWin64_Data/Managed/*.dll">
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Lib.Harmony" Version="2.3.1.1" />
	</ItemGroup>

</Project>
